### ISSUE TITLE
CSI tools (cilksan, cilkscale) segfault when external libraries lack debug info

### ISSUE THREAD

**Issue by timkaler** [wsmoses/Tapir-compiler-rt#5]
I get a segfault when including: https://github.com/jarro2783/cxxopts/blob/master/include/cxxopts.hpp in my csi instrumented program. All that's necessary to reproduce, I believe, is to download and include that header file. 

To see the bug as I see it, you can clone https://github.com/wsmoses/graphtutorial, run 'make', and then execute ./main-cilksan

The output from gdb is the following:
```
Reading symbols from ./main-cilksan...done.
(gdb) tr
No default breakpoint address now.
(gdb) r
Starting program: /home/gridsan/groups/mooc_dev/ModernAlgorithms/Leiserson/tapir-build-test/graphtutorial/main-cilksan 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.25-13.fc26.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
get_fed_entry (csi_id=csi_id@entry=95, fed_type=FED_TYPE_FUNCTIONS) at /home/gridsan/tschardl/mooc_dev_shared/ModernAlgorithms/Leiserson/Tapir-LLVM/projects/compiler-rt/lib/cilksan/csanrt.cpp:144
144	/home/gridsan/tschardl/mooc_dev_shared/ModernAlgorithms/Leiserson/Tapir-LLVM/projects/compiler-rt/lib/cilksan/csanrt.cpp: No such file or directory.
Missing separate debuginfos, use: dnf debuginfo-install libcilkrts-7.3.1-2.fc26.x86_64 libgcc-7.1.1-3.fc26.x86_64 libstdc++-7.1.1-3.fc26.x86_64 snappy-1.1.4-3.fc26.x86_64
(gdb) bt
#0  get_fed_entry (csi_id=csi_id@entry=95, fed_type=FED_TYPE_FUNCTIONS) at /home/gridsan/tschardl/mooc_dev_shared/ModernAlgorithms/Leiserson/Tapir-LLVM/projects/compiler-rt/lib/cilksan/csanrt.cpp:144
#1  __csan_get_func_source_loc (func_id=func_id@entry=95) at /home/gridsan/tschardl/mooc_dev_shared/ModernAlgorithms/Leiserson/Tapir-LLVM/projects/compiler-rt/lib/cilksan/csanrt.cpp:293
#2  0x00002aaaaacf30e8 in __csan_func_entry (func_id=95, sp=0x7fffffffdf70, prop=...)
    at /home/gridsan/tschardl/mooc_dev_shared/ModernAlgorithms/Leiserson/Tapir-LLVM/projects/compiler-rt/lib/cilksan/drivercsan.cpp:184
#3  0x00000000004459de in std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char> >::basic_regex<char const*> (this=<optimized out>, __first=<optimized out>, __last=<optimized out>, __loc=..., 
    __f=(unknown: 16)) at /usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/regex.h:770
#4  0x0000000000403df4 in _GLOBAL__sub_I_main.cpp () at /usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/regex.h:512
#5  0x000000000049d83d in __libc_csu_init ()
#6  0x00002aaaab9ef81b in __libc_start_main () from /lib64/libc.so.6
#7  0x0000000000403efa in _start ()

```

**Comment by timkaler** [comment]
https://github.com/timkaler/graphtutorial
